# --- !Ups

CREATE TABLE "COMPANIES" (
    "ID" INT AUTO_INCREMENT PRIMARY KEY,
    "NAME" VARCHAR NOT NULL,
    "ADDRESS" VARCHAR
);

INSERT INTO "COMPANIES" ("NAME", "ADDRESS") VALUES ('A', 'Tokyo');
INSERT INTO "COMPANIES" ("NAME", "ADDRESS") VALUES ('B', 'Osaka');
INSERT INTO "COMPANIES" ("NAME", "ADDRESS") VALUES ('C', 'Fukuoka');

# --- !Downs

DROP TABLE "COMPANIES";
